// This file is generated by Slice Machine. Update with care!

import CertMenu from './CertMenu';
import CertificateDetails from './CertificateDetails';
import CertificateHero from './CertificateHero';

export {
	CertMenu,
	CertificateDetails,
	CertificateHero,
};

export const components = {
	cert_menu: CertMenu,
	certificate_details: CertificateDetails,
	certificate_hero: CertificateHero,
};
