// This file is generated by Slice Machine. Update with care!

import CertMenu from './CertMenu';
import CertificateBenefits from './CertificateBenefits';
import CertificateDetails from './CertificateDetails';
import CertificateHero from './CertificateHero';
import CertificateInstructor from './CertificateInstructor';
import CertificationCirriculum from './CertificationCirriculum';

export {
	CertMenu,
	CertificateBenefits,
	CertificateDetails,
	CertificateHero,
	CertificateInstructor,
	CertificationCirriculum,
};

export const components = {
	cert_menu: CertMenu,
	certificate_benefits: CertificateBenefits,
	certificate_details: CertificateDetails,
	certificate_hero: CertificateHero,
	certificate_instructor: CertificateInstructor,
	certification_cirriculum: CertificationCirriculum,
};
