/* eslint-disable */
// this is an auto generated file. This will be overwritten

export const onCreateUser = /* GraphQL */ `
  subscription OnCreateUser {
    onCreateUser {
      id
      name
      email
      picture
      companyName
      companyTitle
      linkedin
      cmpmApplication {
        user {
          id
          name
          email
          picture
          companyName
          companyTitle
          linkedin
          createdAt
          updatedAt
          userCmpmApplicationId
        }
        id
        firstName
        lastName
        email
        phone
        streetAddress
        addressExtra
        city
        state
        country
        companyName
        companyTitle
        linkedin
        background
        whyPackaging
        areaOfInterest
        sessionApplying
        referral
        payment
        yearGoals
        cmpmGoals
        moreAboutYou
        createdOn
        updatedOn
        cMPMFormUserId
      }
      createdAt
      updatedAt
      userCmpmApplicationId
    }
  }
`;
export const onUpdateUser = /* GraphQL */ `
  subscription OnUpdateUser {
    onUpdateUser {
      id
      name
      email
      picture
      companyName
      companyTitle
      linkedin
      cmpmApplication {
        user {
          id
          name
          email
          picture
          companyName
          companyTitle
          linkedin
          createdAt
          updatedAt
          userCmpmApplicationId
        }
        id
        firstName
        lastName
        email
        phone
        streetAddress
        addressExtra
        city
        state
        country
        companyName
        companyTitle
        linkedin
        background
        whyPackaging
        areaOfInterest
        sessionApplying
        referral
        payment
        yearGoals
        cmpmGoals
        moreAboutYou
        createdOn
        updatedOn
        cMPMFormUserId
      }
      createdAt
      updatedAt
      userCmpmApplicationId
    }
  }
`;
export const onDeleteUser = /* GraphQL */ `
  subscription OnDeleteUser {
    onDeleteUser {
      id
      name
      email
      picture
      companyName
      companyTitle
      linkedin
      cmpmApplication {
        user {
          id
          name
          email
          picture
          companyName
          companyTitle
          linkedin
          createdAt
          updatedAt
          userCmpmApplicationId
        }
        id
        firstName
        lastName
        email
        phone
        streetAddress
        addressExtra
        city
        state
        country
        companyName
        companyTitle
        linkedin
        background
        whyPackaging
        areaOfInterest
        sessionApplying
        referral
        payment
        yearGoals
        cmpmGoals
        moreAboutYou
        createdOn
        updatedOn
        cMPMFormUserId
      }
      createdAt
      updatedAt
      userCmpmApplicationId
    }
  }
`;
export const onCreateCMPMForm = /* GraphQL */ `
  subscription OnCreateCMPMForm {
    onCreateCMPMForm {
      user {
        id
        name
        email
        picture
        companyName
        companyTitle
        linkedin
        cmpmApplication {
          id
          firstName
          lastName
          email
          phone
          streetAddress
          addressExtra
          city
          state
          country
          companyName
          companyTitle
          linkedin
          background
          whyPackaging
          areaOfInterest
          sessionApplying
          referral
          payment
          yearGoals
          cmpmGoals
          moreAboutYou
          createdOn
          updatedOn
          cMPMFormUserId
        }
        createdAt
        updatedAt
        userCmpmApplicationId
      }
      id
      firstName
      lastName
      email
      phone
      streetAddress
      addressExtra
      city
      state
      country
      companyName
      companyTitle
      linkedin
      background
      whyPackaging
      areaOfInterest
      sessionApplying
      referral
      payment
      yearGoals
      cmpmGoals
      moreAboutYou
      createdOn
      updatedOn
      cMPMFormUserId
    }
  }
`;
export const onUpdateCMPMForm = /* GraphQL */ `
  subscription OnUpdateCMPMForm {
    onUpdateCMPMForm {
      user {
        id
        name
        email
        picture
        companyName
        companyTitle
        linkedin
        cmpmApplication {
          id
          firstName
          lastName
          email
          phone
          streetAddress
          addressExtra
          city
          state
          country
          companyName
          companyTitle
          linkedin
          background
          whyPackaging
          areaOfInterest
          sessionApplying
          referral
          payment
          yearGoals
          cmpmGoals
          moreAboutYou
          createdOn
          updatedOn
          cMPMFormUserId
        }
        createdAt
        updatedAt
        userCmpmApplicationId
      }
      id
      firstName
      lastName
      email
      phone
      streetAddress
      addressExtra
      city
      state
      country
      companyName
      companyTitle
      linkedin
      background
      whyPackaging
      areaOfInterest
      sessionApplying
      referral
      payment
      yearGoals
      cmpmGoals
      moreAboutYou
      createdOn
      updatedOn
      cMPMFormUserId
    }
  }
`;
export const onDeleteCMPMForm = /* GraphQL */ `
  subscription OnDeleteCMPMForm {
    onDeleteCMPMForm {
      user {
        id
        name
        email
        picture
        companyName
        companyTitle
        linkedin
        cmpmApplication {
          id
          firstName
          lastName
          email
          phone
          streetAddress
          addressExtra
          city
          state
          country
          companyName
          companyTitle
          linkedin
          background
          whyPackaging
          areaOfInterest
          sessionApplying
          referral
          payment
          yearGoals
          cmpmGoals
          moreAboutYou
          createdOn
          updatedOn
          cMPMFormUserId
        }
        createdAt
        updatedAt
        userCmpmApplicationId
      }
      id
      firstName
      lastName
      email
      phone
      streetAddress
      addressExtra
      city
      state
      country
      companyName
      companyTitle
      linkedin
      background
      whyPackaging
      areaOfInterest
      sessionApplying
      referral
      payment
      yearGoals
      cmpmGoals
      moreAboutYou
      createdOn
      updatedOn
      cMPMFormUserId
    }
  }
`;
